/**
 * Données de démonstration (« seed ») pour l'agrégateur d'offres d'emploi québécois.
 *
 * Fichier totalement autonome : aucune dépendance externe, aucun import.
 * Utilisé par `seed.ts` pour peupler la base hors-ligne avec un jeu d'offres
 * réalistes couvrant toutes les régions et catégories du Québec.
 */

export interface SeedJob {
  sourceId: string;
  url: string;
  title: string;
  company: string;
  location?: string;
  regionId?: string;
  city?: string;
  remote?: "presentiel" | "hybride" | "teletravail";
  categoryId?: string;
  employmentType?: "temps-plein" | "temps-partiel" | "contrat" | "stage" | "saisonnier" | "occasionnel";
  salaryMin?: number;
  salaryMax?: number;
  salaryPeriod?: "heure" | "semaine" | "mois" | "annee";
  description?: string;
  tags?: string[];
  languages?: ("fr" | "en" | "bilingue")[];
  postedDaysAgo?: number;
}

export const SEED_JOBS: SeedJob[] = [
  // --- Technologies de l'information (TI) -----------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518401-developpeur-full-stack",
    title: "Développeur(euse) full stack",
    company: "CGI",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 68000,
    salaryMax: 95000,
    salaryPeriod: "annee",
    description:
      "Rejoignez l'équipe TI de CGI pour concevoir et développer des applications web modernes pour une clientèle variée. Vous travaillerez au sein d'une équipe agile sur des projets stimulants à fort impact.",
    tags: ["JavaScript", "React", "Node.js", "Agile"],
    languages: ["bilingue"],
    postedDaysAgo: 3,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518402-analyste-programmeur-dotnet",
    title: "Analyste programmeur(euse) .NET",
    company: "CGI",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 58000,
    salaryMax: 82000,
    salaryPeriod: "annee",
    description:
      "CGI recherche un(e) analyste programmeur(euse) .NET pour maintenir et améliorer des applications d'entreprise critiques. Le poste implique la collaboration avec des équipes multidisciplinaires à Québec.",
    tags: ["C#", ".NET", "SQL Server", "Azure"],
    languages: ["fr"],
    postedDaysAgo: 12,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518403-developpeur-back-end-nodejs",
    title: "Développeur(euse) back-end Node.js",
    company: "Lightspeed",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 78000,
    salaryMax: 115000,
    salaryPeriod: "annee",
    description:
      "Lightspeed est à la recherche d'un(e) développeur(euse) back-end pour renforcer son équipe produit en pleine croissance. Vous concevrez des API performantes utilisées par des milliers de commerçants.",
    tags: ["Node.js", "TypeScript", "PostgreSQL", "microservices"],
    languages: ["bilingue"],
    postedDaysAgo: 5,
  },
  {
    sourceId: "espresso-jobs",
    url: "https://www.espresso-jobs.com/fr/emplois/ingenieur-logiciel-ia-90311.html",
    title: "Ingénieur(e) logiciel IA",
    company: "Coveo",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "hybride",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 82000,
    salaryMax: 122000,
    salaryPeriod: "annee",
    description:
      "Coveo cherche un(e) ingénieur(e) logiciel passionné(e) par l'intelligence artificielle pour améliorer ses moteurs de recherche et de recommandation. Vous travaillerez avec des technologies de pointe en apprentissage automatique.",
    tags: ["Machine Learning", "Python", "Java", "recherche"],
    languages: ["bilingue"],
    postedDaysAgo: 8,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518404-developpeur-mobile-ios-android",
    title: "Développeur(euse) mobile iOS/Android",
    company: "Nuvei",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 72000,
    salaryMax: 102000,
    salaryPeriod: "annee",
    description:
      "Nuvei souhaite embaucher un(e) développeur(euse) mobile pour bâtir des solutions de paiement fiables sur iOS et Android. Vous collaborerez étroitement avec les équipes produit et design.",
    tags: ["Swift", "Kotlin", "React Native", "API REST"],
    languages: ["bilingue"],
    postedDaysAgo: 15,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518405-programmeur-gameplay",
    title: "Programmeur(euse) gameplay",
    company: "Ubisoft Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 68000,
    salaryMax: 98000,
    salaryPeriod: "annee",
    description:
      "Ubisoft Montréal recrute un(e) programmeur(euse) gameplay pour donner vie à des mécaniques de jeu innovantes. Vous travaillerez en étroite collaboration avec les designers et artistes du studio.",
    tags: ["C++", "Unreal Engine", "jeux vidéo", "gameplay"],
    languages: ["bilingue"],
    postedDaysAgo: 20,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518406-architecte-solutions-ti",
    title: "Architecte de solutions TI",
    company: "Desjardins",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "ti",
    employmentType: "temps-plein",
    salaryMin: 92000,
    salaryMax: 132000,
    salaryPeriod: "annee",
    description:
      "Desjardins recherche un(e) architecte de solutions TI pour concevoir des architectures évolutives et sécuritaires. Vous jouerez un rôle clé dans la transformation numérique de l'organisation.",
    tags: ["architecture logicielle", "cloud", "Azure", "microservices"],
    languages: ["bilingue"],
    postedDaysAgo: 2,
  },
  {
    sourceId: "quebec-emploi",
    url: "https://placement.emploiquebec.gouv.qc.ca/mbe/ut/offre/6601123",
    title: "Analyste en cybersécurité",
    company: "Banque Nationale",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "ti",
    employmentType: "contrat",
    salaryMin: 74000,
    salaryMax: 108000,
    salaryPeriod: "annee",
    description:
      "Banque Nationale est à la recherche d'un(e) analyste en cybersécurité pour surveiller et renforcer la posture de sécurité de ses systèmes. Le rôle inclut la détection et la réponse aux incidents.",
    tags: ["cybersécurité", "SIEM", "gestion des risques", "conformité"],
    languages: ["bilingue"],
    postedDaysAgo: 25,
  },

  // --- Génie -------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518407-ingenieur-aerospatiale",
    title: "Ingénieur(e) en aérospatiale",
    company: "Bombardier",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "genie",
    employmentType: "temps-plein",
    salaryMin: 76000,
    salaryMax: 108000,
    salaryPeriod: "annee",
    description:
      "Bombardier recherche un(e) ingénieur(e) en aérospatiale pour participer à la conception de composants d'aéronefs d'affaires. Vous collaborerez avec des équipes techniques multidisciplinaires.",
    tags: ["aérospatiale", "CATIA", "conception mécanique", "aéronautique"],
    languages: ["bilingue"],
    postedDaysAgo: 6,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518408-ingenieur-civil-infrastructures",
    title: "Ingénieur(e) civil(e) - infrastructures",
    company: "AtkinsRéalis (SNC-Lavalin)",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "genie",
    employmentType: "temps-plein",
    salaryMin: 70000,
    salaryMax: 100000,
    salaryPeriod: "annee",
    description:
      "AtkinsRéalis recrute un(e) ingénieur(e) civil(e) pour la conception de projets d'infrastructures municipales et routières. Vous serez impliqué(e) dans toutes les phases du cycle de vie des projets.",
    tags: ["génie civil", "infrastructures", "AutoCAD", "gestion de projet"],
    languages: ["bilingue"],
    postedDaysAgo: 18,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518409-ingenieur-simulation",
    title: "Ingénieur(e) en simulation",
    company: "CAE",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "genie",
    employmentType: "temps-plein",
    salaryMin: 73000,
    salaryMax: 108000,
    salaryPeriod: "annee",
    description:
      "CAE recherche un(e) ingénieur(e) en simulation pour développer des systèmes de simulation de vol de haute fidélité. Vous travaillerez sur des projets à la fine pointe de la technologie aéronautique.",
    tags: ["simulation", "aéronautique", "MATLAB", "modélisation"],
    languages: ["bilingue"],
    postedDaysAgo: 10,
  },
  {
    sourceId: "guichet-emplois",
    url: "https://www.guichetemplois.gc.ca/emploidetail/37452201",
    title: "Ingénieur(e) mécanique - conception",
    company: "Pratt & Whitney Canada",
    location: "Longueuil, Québec",
    regionId: "monteregie",
    city: "Longueuil",
    remote: "presentiel",
    categoryId: "genie",
    employmentType: "temps-plein",
    salaryMin: 69000,
    salaryMax: 98000,
    salaryPeriod: "annee",
    description:
      "Pratt & Whitney Canada est à la recherche d'un(e) ingénieur(e) mécanique pour concevoir des composants de moteurs d'avion. Vous participerez à des projets d'innovation en propulsion aéronautique.",
    tags: ["conception mécanique", "SolidWorks", "turbines", "aéronautique"],
    languages: ["bilingue"],
    postedDaysAgo: 22,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518410-ingenieur-electrique-reseaux",
    title: "Ingénieur(e) électrique - réseaux",
    company: "Hydro-Québec",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "genie",
    employmentType: "temps-plein",
    salaryMin: 75000,
    salaryMax: 112000,
    salaryPeriod: "annee",
    description:
      "Hydro-Québec recherche un(e) ingénieur(e) électrique pour optimiser la fiabilité du réseau de transport d'électricité. Vous contribuerez à des projets d'envergure pour la transition énergétique du Québec.",
    tags: ["réseaux électriques", "haute tension", "AutoCAD", "génie électrique"],
    languages: ["fr"],
    postedDaysAgo: 14,
  },

  // --- Santé ---------------------------------------------------------------
  {
    sourceId: "recrutement-sante",
    url: "https://www.recrutementsante.gouv.qc.ca/offre/15001",
    title: "Infirmier(ère) clinicien(ne) - urgence",
    company: "CHUM",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 30,
    salaryMax: 44,
    salaryPeriod: "heure",
    description:
      "Le CHUM recherche un(e) infirmier(ère) clinicien(ne) pour son service d'urgence achalandé. Vous prodiguerez des soins de qualité dans un environnement dynamique et stimulant.",
    tags: ["soins infirmiers", "urgence", "OIIQ", "travail d'équipe"],
    languages: ["fr"],
    postedDaysAgo: 4,
  },
  {
    sourceId: "recrutement-sante",
    url: "https://www.recrutementsante.gouv.qc.ca/offre/15002",
    title: "Préposé(e) aux bénéficiaires",
    company: "CIUSSS du Centre-Sud-de-l'Île-de-Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 21,
    salaryMax: 26,
    salaryPeriod: "heure",
    description:
      "Le CIUSSS du Centre-Sud-de-l'Île-de-Montréal recherche un(e) préposé(e) aux bénéficiaires pour accompagner les résidents dans leurs activités quotidiennes. Empathie et sens du travail d'équipe sont essentiels.",
    tags: ["soins aux patients", "CHSLD", "empathie", "travail d'équipe"],
    languages: ["fr"],
    postedDaysAgo: 1,
  },
  {
    sourceId: "recrutement-sante",
    url: "https://www.recrutementsante.gouv.qc.ca/offre/15003",
    title: "Infirmier(ère) auxiliaire",
    company: "CIUSSS de l'Estrie - CHUS",
    location: "Sherbrooke, Québec",
    regionId: "estrie",
    city: "Sherbrooke",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 24,
    salaryMax: 31,
    salaryPeriod: "heure",
    description:
      "Le CIUSSS de l'Estrie - CHUS recrute un(e) infirmier(ère) auxiliaire pour ses unités de soins. Vous travaillerez en étroite collaboration avec l'équipe soignante pour assurer des soins sécuritaires.",
    tags: ["soins infirmiers", "OIIAQ", "CLSC", "rigueur"],
    languages: ["fr"],
    postedDaysAgo: 9,
  },
  {
    sourceId: "recrutement-sante",
    url: "https://www.recrutementsante.gouv.qc.ca/offre/15004",
    title: "Technologue en radiologie",
    company: "CHU de Québec-Université Laval",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 28,
    salaryMax: 38,
    salaryPeriod: "heure",
    description:
      "Le CHU de Québec-Université Laval recherche un(e) technologue en radiologie pour réaliser des examens d'imagerie médicale. Le poste requiert rigueur et souci du détail.",
    tags: ["imagerie médicale", "radiologie", "OTIMROEPMQ", "rigueur"],
    languages: ["fr"],
    postedDaysAgo: 16,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518411-travailleur-social",
    title: "Travailleur(euse) social(e)",
    company: "CISSS de la Montérégie-Centre",
    location: "Longueuil, Québec",
    regionId: "monteregie",
    city: "Longueuil",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 27,
    salaryMax: 36,
    salaryPeriod: "heure",
    description:
      "Le CISSS de la Montérégie-Centre recherche un(e) travailleur(euse) social(e) pour intervenir auprès de clientèles vulnérables. Vous effectuerez des évaluations psychosociales et coordonnerez les services requis.",
    tags: ["intervention sociale", "OTSTCFQ", "relation d'aide", "évaluation psychosociale"],
    languages: ["fr"],
    postedDaysAgo: 27,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518412-infirmier-clinicien-soins-domicile",
    title: "Infirmier(ère) clinicien(ne) - soins à domicile",
    company: "CIUSSS du Centre-Sud-de-l'Île-de-Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 30,
    salaryMax: 44,
    salaryPeriod: "heure",
    description:
      "Le CIUSSS du Centre-Sud-de-l'Île-de-Montréal recherche un(e) infirmier(ère) clinicien(ne) pour son programme de soutien à domicile. Vous offrirez des soins spécialisés directement chez les usagers.",
    tags: ["soins à domicile", "OIIQ", "autonomie", "soins infirmiers"],
    languages: ["fr"],
    postedDaysAgo: 7,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518413-physiotherapeute",
    title: "Physiothérapeute",
    company: "CIUSSS de la Mauricie-et-du-Centre-du-Québec",
    location: "Trois-Rivières, Québec",
    regionId: "mauricie",
    city: "Trois-Rivières",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 68000,
    salaryMax: 92000,
    salaryPeriod: "annee",
    description:
      "Le CIUSSS de la Mauricie-et-du-Centre-du-Québec recherche un(e) physiothérapeute pour évaluer et traiter une clientèle variée. Vous élaborerez des plans de traitement personnalisés en réadaptation.",
    tags: ["réadaptation", "OPPQ", "évaluation physique", "rééducation"],
    languages: ["fr"],
    postedDaysAgo: 19,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518414-pharmacien-etablissement",
    title: "Pharmacien(ne) d'établissement",
    company: "CIUSSS de la Capitale-Nationale",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "sante",
    employmentType: "temps-plein",
    salaryMin: 98000,
    salaryMax: 128000,
    salaryPeriod: "annee",
    description:
      "Le CIUSSS de la Capitale-Nationale recherche un(e) pharmacien(ne) d'établissement pour assurer la gestion sécuritaire de la thérapie médicamenteuse. Vous collaborerez étroitement avec l'équipe médicale.",
    tags: ["pharmacie hospitalière", "OPQ", "gestion médicamenteuse", "soins pharmaceutiques"],
    languages: ["fr"],
    postedDaysAgo: 11,
  },

  // --- Construction ----------------------------------------------------------
  {
    sourceId: "ccq-construction",
    url: "https://www.ccq.org/fr/carrieres/offres/7701-charge-de-projet-construction",
    title: "Chargé(e) de projet en construction",
    company: "Pomerleau",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "temps-plein",
    salaryMin: 72000,
    salaryMax: 98000,
    salaryPeriod: "annee",
    description:
      "Pomerleau recherche un(e) chargé(e) de projet pour piloter des chantiers de construction commerciale et institutionnelle. Vous coordonnerez les équipes, les échéanciers et les budgets.",
    tags: ["gestion de projet", "construction", "MS Project", "budget"],
    languages: ["bilingue"],
    postedDaysAgo: 5,
  },
  {
    sourceId: "ccq-construction",
    url: "https://www.ccq.org/fr/carrieres/offres/7702-surintendant-de-chantier",
    title: "Surintendant(e) de chantier",
    company: "EBC",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "temps-plein",
    salaryMin: 76000,
    salaryMax: 105000,
    salaryPeriod: "annee",
    description:
      "EBC recrute un(e) surintendant(e) de chantier pour superviser les opérations quotidiennes d'un grand projet d'infrastructure. La sécurité et le respect des échéanciers seront vos priorités.",
    tags: ["supervision de chantier", "santé-sécurité", "planification", "construction"],
    languages: ["fr"],
    postedDaysAgo: 13,
  },
  {
    sourceId: "ccq-construction",
    url: "https://www.ccq.org/fr/carrieres/offres/7703-charpentier-menuisier",
    title: "Charpentier(ère)-menuisier(ère)",
    company: "Pomerleau",
    location: "Gatineau, Québec",
    regionId: "outaouais",
    city: "Gatineau",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "temps-plein",
    salaryMin: 28,
    salaryMax: 42,
    salaryPeriod: "heure",
    description:
      "Pomerleau recherche un(e) charpentier(ère)-menuisier(ère) qualifié(e) pour ses chantiers en Outaouais. Vous travaillerez sur la structure et le coffrage de divers bâtiments.",
    tags: ["charpenterie", "CCQ", "lecture de plans", "coffrage"],
    languages: ["fr"],
    postedDaysAgo: 21,
  },
  {
    sourceId: "ccq-construction",
    url: "https://www.ccq.org/fr/carrieres/offres/7704-grutier",
    title: "Grutier(ère)",
    company: "EBC",
    location: "Chibougamau, Québec",
    regionId: "nord-du-quebec",
    city: "Chibougamau",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "contrat",
    salaryMin: 32,
    salaryMax: 48,
    salaryPeriod: "heure",
    description:
      "EBC recherche un(e) grutier(ère) expérimenté(e) pour un projet d'envergure dans le Nord-du-Québec. La carte de compétence CCQ est requise.",
    tags: ["grue mobile", "CCQ", "sécurité", "levage"],
    languages: ["fr"],
    postedDaysAgo: 3,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518415-monteur-acier-structure",
    title: "Monteur(euse) d'acier de structure",
    company: "Canam",
    location: "Saint-Georges, Québec",
    regionId: "chaudiere-appalaches",
    city: "Saint-Georges",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "temps-plein",
    salaryMin: 26,
    salaryMax: 40,
    salaryPeriod: "heure",
    description:
      "Canam recherche un(e) monteur(euse) d'acier de structure pour l'assemblage de charpentes métalliques sur divers chantiers. Le travail en hauteur et le respect des normes de sécurité sont essentiels.",
    tags: ["acier de structure", "CCQ", "soudure", "montage"],
    languages: ["fr"],
    postedDaysAgo: 24,
  },
  {
    sourceId: "espresso-jobs",
    url: "https://www.espresso-jobs.com/fr/emplois/electricien-industriel-90312.html",
    title: "Électricien(ne) industriel(le)",
    company: "Construction Bau-Val",
    location: "Rouyn-Noranda, Québec",
    regionId: "abitibi-temiscamingue",
    city: "Rouyn-Noranda",
    remote: "presentiel",
    categoryId: "construction",
    employmentType: "temps-plein",
    salaryMin: 31,
    salaryMax: 46,
    salaryPeriod: "heure",
    description:
      "Construction Bau-Val recrute un(e) électricien(ne) industriel(le) pour l'installation et l'entretien de systèmes électriques en milieu industriel. Une expérience en automatisation est un atout.",
    tags: ["électricité industrielle", "CCQ", "automatisation", "dépannage"],
    languages: ["fr"],
    postedDaysAgo: 17,
  },

  // --- Finance ---------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518416-conseiller-financier",
    title: "Conseiller(ère) financier(ère)",
    company: "Desjardins",
    location: "Lévis, Québec",
    regionId: "chaudiere-appalaches",
    city: "Lévis",
    remote: "hybride",
    categoryId: "finance",
    employmentType: "temps-plein",
    salaryMin: 52000,
    salaryMax: 78000,
    salaryPeriod: "annee",
    description:
      "Desjardins recherche un(e) conseiller(ère) financier(ère) pour accompagner les membres dans la gestion de leurs finances personnelles. Vous offrirez des conseils adaptés à leurs besoins et objectifs.",
    tags: ["placements", "service à la clientèle", "planification financière", "AMF"],
    languages: ["bilingue"],
    postedDaysAgo: 8,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518417-analyste-financier",
    title: "Analyste financier(ère)",
    company: "Banque Nationale",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "finance",
    employmentType: "temps-plein",
    salaryMin: 58000,
    salaryMax: 85000,
    salaryPeriod: "annee",
    description:
      "Banque Nationale recherche un(e) analyste financier(ère) pour produire des analyses et des rapports soutenant la prise de décision d'affaires. Vous travaillerez en étroite collaboration avec plusieurs équipes internes.",
    tags: ["analyse financière", "Excel", "modélisation", "reporting"],
    languages: ["bilingue"],
    postedDaysAgo: 6,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518418-actuaire",
    title: "Actuaire",
    company: "iA Groupe financier",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "hybride",
    categoryId: "finance",
    employmentType: "temps-plein",
    salaryMin: 76000,
    salaryMax: 118000,
    salaryPeriod: "annee",
    description:
      "iA Groupe financier recherche un(e) actuaire pour évaluer les risques et développer des modèles financiers. Vous progresserez dans votre cheminement vers le titre de Fellow tout en étant soutenu(e) par l'employeur.",
    tags: ["actuariat", "gestion des risques", "Excel", "statistiques"],
    languages: ["bilingue"],
    postedDaysAgo: 30,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518419-conseiller-assurance-dommages",
    title: "Conseiller(ère) en assurance de dommages",
    company: "La Capitale",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "finance",
    employmentType: "temps-plein",
    salaryMin: 48000,
    salaryMax: 68000,
    salaryPeriod: "annee",
    description:
      "La Capitale recherche un(e) conseiller(ère) en assurance de dommages pour offrir des conseils personnalisés à la clientèle. Le poste est offert en télétravail avec un horaire flexible.",
    tags: ["assurance", "service client", "AMF", "négociation"],
    languages: ["fr"],
    postedDaysAgo: 2,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518420-analyste-credit-commercial",
    title: "Analyste - crédit commercial",
    company: "Desjardins",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "finance",
    employmentType: "temps-plein",
    salaryMin: 62000,
    salaryMax: 88000,
    salaryPeriod: "annee",
    description:
      "Desjardins recherche un(e) analyste en crédit commercial pour évaluer la solvabilité des entreprises clientes. Vous participerez à l'analyse et à la recommandation de dossiers de financement.",
    tags: ["crédit commercial", "analyse financière", "gestion du risque", "Excel"],
    languages: ["bilingue"],
    postedDaysAgo: 26,
  },

  // --- Administration ----------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518421-agent-de-bureau",
    title: "Agent(e) de bureau",
    company: "Ville de Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "admin",
    employmentType: "temps-plein",
    salaryMin: 22,
    salaryMax: 28,
    salaryPeriod: "heure",
    description:
      "La Ville de Montréal recherche un(e) agent(e) de bureau pour soutenir les opérations administratives d'un arrondissement. Le poste requiert une bonne maîtrise des outils bureautiques.",
    tags: ["bureautique", "service à la clientèle", "Word", "organisation"],
    languages: ["fr"],
    postedDaysAgo: 10,
  },
  {
    sourceId: "espresso-jobs",
    url: "https://www.espresso-jobs.com/fr/emplois/adjoint-administratif-90313.html",
    title: "Adjoint(e) administratif(ve)",
    company: "Hydro-Québec",
    location: "Gatineau, Québec",
    regionId: "outaouais",
    city: "Gatineau",
    remote: "presentiel",
    categoryId: "admin",
    employmentType: "temps-plein",
    salaryMin: 24,
    salaryMax: 30,
    salaryPeriod: "heure",
    description:
      "Hydro-Québec recherche un(e) adjoint(e) administratif(ve) pour soutenir une équipe d'ingénierie basée à Gatineau. Vous gérerez les agendas, la correspondance et divers dossiers administratifs.",
    tags: ["soutien administratif", "Office", "organisation", "rédaction"],
    languages: ["fr"],
    postedDaysAgo: 14,
  },
  {
    sourceId: "jobboom",
    url: "https://www.jobboom.com/fr/emploi/coordonnateur-administratif/244001",
    title: "Coordonnateur(trice) administratif(ve)",
    company: "Sépaq",
    location: "Mont-Tremblant, Québec",
    regionId: "laurentides",
    city: "Mont-Tremblant",
    remote: "presentiel",
    categoryId: "admin",
    employmentType: "temps-partiel",
    salaryMin: 21,
    salaryMax: 27,
    salaryPeriod: "heure",
    description:
      "La Sépaq recherche un(e) coordonnateur(trice) administratif(ve) pour le parc national du Mont-Tremblant. Vous appuierez la direction dans la gestion quotidienne des opérations.",
    tags: ["coordination", "service client", "Office", "organisation"],
    languages: ["fr"],
    postedDaysAgo: 33,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518422-technicien-en-administration",
    title: "Technicien(ne) en administration",
    company: "Ville de Québec",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "admin",
    employmentType: "temps-plein",
    salaryMin: 42000,
    salaryMax: 56000,
    salaryPeriod: "annee",
    description:
      "La Ville de Québec recherche un(e) technicien(ne) en administration pour soutenir divers services municipaux. Vous serez responsable du suivi de dossiers et de la gestion documentaire.",
    tags: ["administration publique", "gestion documentaire", "Excel", "rigueur"],
    languages: ["fr"],
    postedDaysAgo: 19,
  },

  // --- Vente -------------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518423-conseiller-en-vente",
    title: "Conseiller(ère) en vente",
    company: "Metro",
    location: "Laval, Québec",
    regionId: "laval",
    city: "Laval",
    remote: "presentiel",
    categoryId: "vente",
    employmentType: "temps-plein",
    salaryMin: 18,
    salaryMax: 24,
    salaryPeriod: "heure",
    description:
      "Metro recherche un(e) conseiller(ère) en vente dynamique pour offrir un service à la clientèle exceptionnel en magasin. Une attitude positive et un bon esprit d'équipe sont recherchés.",
    tags: ["service à la clientèle", "vente au détail", "caisse", "travail d'équipe"],
    languages: ["fr"],
    postedDaysAgo: 4,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518424-representant-des-ventes",
    title: "Représentant(e) des ventes",
    company: "Couche-Tard",
    location: "Trois-Rivières, Québec",
    regionId: "mauricie",
    city: "Trois-Rivières",
    remote: "presentiel",
    categoryId: "vente",
    employmentType: "temps-plein",
    salaryMin: 45000,
    salaryMax: 65000,
    salaryPeriod: "annee",
    description:
      "Couche-Tard recherche un(e) représentant(e) des ventes pour développer sa clientèle commerciale dans la région de la Mauricie. Vous serez responsable d'atteindre des objectifs de vente ambitieux.",
    tags: ["développement des affaires", "négociation", "service client", "permis de conduire"],
    languages: ["fr"],
    postedDaysAgo: 12,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518425-conseiller-en-vin",
    title: "Conseiller(ère) en vin",
    company: "SAQ",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "vente",
    employmentType: "occasionnel",
    salaryMin: 17,
    salaryMax: 23,
    salaryPeriod: "heure",
    description:
      "La SAQ recherche un(e) conseiller(ère) en vin passionné(e) pour guider la clientèle dans ses choix. Une bonne connaissance des vins et spiritueux est un atout important.",
    tags: ["connaissance des vins", "service à la clientèle", "conseil", "vente"],
    languages: ["fr"],
    postedDaysAgo: 28,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518426-representant-vente-detail",
    title: "Représentant(e) vente au détail",
    company: "Jean Coutu",
    location: "Sherbrooke, Québec",
    regionId: "estrie",
    city: "Sherbrooke",
    remote: "presentiel",
    categoryId: "vente",
    employmentType: "saisonnier",
    salaryMin: 16,
    salaryMax: 21,
    salaryPeriod: "heure",
    description:
      "Jean Coutu recherche un(e) représentant(e) vente au détail pour la période des Fêtes. Vous offrirez un service à la clientèle chaleureux et efficace en pharmacie.",
    tags: ["vente au détail", "service client", "caisse", "dynamisme"],
    languages: ["fr"],
    postedDaysAgo: 40,
  },

  // --- Marketing ---------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518427-stratege-marketing",
    title: "Stratège marketing",
    company: "Cossette",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "marketing",
    employmentType: "temps-plein",
    salaryMin: 55000,
    salaryMax: 80000,
    salaryPeriod: "annee",
    description:
      "Cossette recherche un(e) stratège marketing pour élaborer des stratégies de marque percutantes pour des clients variés. Vous collaborerez avec des équipes créatives et de comptes.",
    tags: ["stratégie de marque", "publicité", "analyse de marché", "créativité"],
    languages: ["bilingue"],
    postedDaysAgo: 9,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518428-charge-projet-marketing-numerique",
    title: "Chargé(e) de projet marketing numérique",
    company: "Loto-Québec",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "marketing",
    employmentType: "contrat",
    salaryMin: 58000,
    salaryMax: 82000,
    salaryPeriod: "annee",
    description:
      "Loto-Québec recherche un(e) chargé(e) de projet marketing numérique pour piloter des campagnes multiplateformes. Vous coordonnerez les parties prenantes internes et externes tout au long du projet.",
    tags: ["marketing numérique", "gestion de projet", "SEO", "analytique web"],
    languages: ["bilingue"],
    postedDaysAgo: 15,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518429-specialiste-marketing",
    title: "Spécialiste marketing",
    company: "Couche-Tard",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "marketing",
    employmentType: "temps-plein",
    salaryMin: 52000,
    salaryMax: 75000,
    salaryPeriod: "annee",
    description:
      "Couche-Tard recherche un(e) spécialiste marketing pour soutenir le déploiement de campagnes de marque à l'échelle nationale. Le poste est offert entièrement en télétravail.",
    tags: ["marketing de marque", "réseaux sociaux", "analytique", "créativité"],
    languages: ["bilingue"],
    postedDaysAgo: 23,
  },

  // --- Ressources humaines (RH) --------------------------------------------------------
  {
    sourceId: "randstad-ca",
    url: "https://www.randstad.ca/fr/emplois/conseiller-en-recrutement/987601/",
    title: "Conseiller(ère) en recrutement",
    company: "Randstad Canada",
    location: "Ottawa, Ontario",
    regionId: "canada-autre",
    city: "Ottawa",
    remote: "hybride",
    categoryId: "rh",
    employmentType: "temps-plein",
    salaryMin: 48000,
    salaryMax: 68000,
    salaryPeriod: "annee",
    description:
      "Randstad Canada recherche un(e) conseiller(ère) en recrutement pour dénicher les meilleurs talents pour ses clients. Vous gérerez le cycle complet de recrutement, de la recherche à l'embauche.",
    tags: ["recrutement", "entrevues", "relations clients", "sourcing"],
    languages: ["bilingue"],
    postedDaysAgo: 1,
  },
  {
    sourceId: "randstad-ca",
    url: "https://www.randstad.ca/fr/emplois/generaliste-rh/987602/",
    title: "Généraliste RH",
    company: "Sollio Groupe Coopératif",
    location: "Longueuil, Québec",
    regionId: "monteregie",
    city: "Longueuil",
    remote: "presentiel",
    categoryId: "rh",
    employmentType: "temps-plein",
    salaryMin: 55000,
    salaryMax: 75000,
    salaryPeriod: "annee",
    description:
      "Sollio Groupe Coopératif recherche un(e) généraliste RH pour soutenir les gestionnaires dans la gestion des ressources humaines. Vous interviendrez sur la dotation, les relations de travail et le développement organisationnel.",
    tags: ["relations de travail", "dotation", "gestion RH", "SIRH"],
    languages: ["fr"],
    postedDaysAgo: 17,
  },
  {
    sourceId: "randstad-ca",
    url: "https://www.randstad.ca/fr/emplois/specialiste-acquisition-talents/987603/",
    title: "Spécialiste en acquisition de talents",
    company: "Garda World",
    location: "Télétravail",
    regionId: "teletravail",
    remote: "teletravail",
    categoryId: "rh",
    employmentType: "contrat",
    salaryMin: 50000,
    salaryMax: 70000,
    salaryPeriod: "annee",
    description:
      "Garda World recherche un(e) spécialiste en acquisition de talents pour soutenir sa croissance rapide. Vous développerez des stratégies de sourcing innovantes pour attirer les meilleurs candidats.",
    tags: ["recrutement", "sourcing", "LinkedIn Recruiter", "entrevues"],
    languages: ["bilingue"],
    postedDaysAgo: 31,
  },

  // --- Éducation ----------------------------------------------------------------
  {
    sourceId: "guichet-emplois",
    url: "https://www.guichetemplois.gc.ca/emploidetail/37452202",
    title: "Enseignant(e) au primaire",
    company: "Centre de services scolaire de Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "education",
    employmentType: "temps-plein",
    salaryMin: 48000,
    salaryMax: 88000,
    salaryPeriod: "annee",
    description:
      "Le Centre de services scolaire de Montréal recherche un(e) enseignant(e) au primaire pour la prochaine année scolaire. Vous favoriserez la réussite éducative d'une classe diversifiée.",
    tags: ["pédagogie", "gestion de classe", "brevet d'enseignement", "planification"],
    languages: ["fr"],
    postedDaysAgo: 20,
  },
  {
    sourceId: "guichet-emplois",
    url: "https://www.guichetemplois.gc.ca/emploidetail/37452203",
    title: "Enseignant(e) en techniques informatiques",
    company: "Cégep de Sherbrooke",
    location: "Sherbrooke, Québec",
    regionId: "estrie",
    city: "Sherbrooke",
    remote: "presentiel",
    categoryId: "education",
    employmentType: "temps-partiel",
    salaryMin: 45000,
    salaryMax: 72000,
    salaryPeriod: "annee",
    description:
      "Le Cégep de Sherbrooke recherche un(e) enseignant(e) en techniques informatiques pour former la relève technologique. Une expérience professionnelle en développement logiciel est un atout.",
    tags: ["enseignement collégial", "informatique", "pédagogie", "programmation"],
    languages: ["fr"],
    postedDaysAgo: 35,
  },
  {
    sourceId: "guichet-emplois",
    url: "https://www.guichetemplois.gc.ca/emploidetail/37452204",
    title: "Chargé(e) de cours - génie logiciel",
    company: "Université Laval",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "presentiel",
    categoryId: "education",
    employmentType: "occasionnel",
    salaryMin: 3500,
    salaryMax: 5200,
    salaryPeriod: "mois",
    description:
      "L'Université Laval recherche un(e) chargé(e) de cours en génie logiciel pour la prochaine session. Vous transmettrez vos connaissances pratiques à une cohorte d'étudiants motivés.",
    tags: ["enseignement universitaire", "génie logiciel", "pédagogie", "recherche"],
    languages: ["fr"],
    postedDaysAgo: 42,
  },

  // --- Juridique ---------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518430-parajuriste",
    title: "Parajuriste",
    company: "BCF Avocats d'affaires",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "juridique",
    employmentType: "temps-plein",
    salaryMin: 50000,
    salaryMax: 70000,
    salaryPeriod: "annee",
    description:
      "BCF Avocats d'affaires recherche un(e) parajuriste pour soutenir son équipe en droit corporatif. Vous participerez à la rédaction de documents juridiques et à la recherche.",
    tags: ["droit corporatif", "recherche juridique", "rédaction", "rigueur"],
    languages: ["bilingue"],
    postedDaysAgo: 6,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518431-conseiller-juridique",
    title: "Conseiller(ère) juridique",
    company: "Ville de Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "juridique",
    employmentType: "temps-plein",
    salaryMin: 72000,
    salaryMax: 105000,
    salaryPeriod: "annee",
    description:
      "La Ville de Montréal recherche un(e) conseiller(ère) juridique pour soutenir divers services municipaux. Vous rédigerez et réviserez des contrats tout en offrant des avis juridiques.",
    tags: ["droit municipal", "rédaction de contrats", "litige", "conformité"],
    languages: ["fr"],
    postedDaysAgo: 29,
  },

  // --- Logistique --------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518432-coordonnateur-logistique",
    title: "Coordonnateur(trice) logistique",
    company: "Metro",
    location: "Laval, Québec",
    regionId: "laval",
    city: "Laval",
    remote: "presentiel",
    categoryId: "logistique",
    employmentType: "temps-plein",
    salaryMin: 50000,
    salaryMax: 68000,
    salaryPeriod: "annee",
    description:
      "Metro recherche un(e) coordonnateur(trice) logistique pour optimiser la gestion des inventaires et des livraisons. Vous collaborerez avec les équipes d'entrepôt et de transport.",
    tags: ["gestion des stocks", "chaîne d'approvisionnement", "Excel", "planification"],
    languages: ["fr"],
    postedDaysAgo: 11,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518433-repartiteur",
    title: "Répartiteur(trice)",
    company: "Garda World",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "presentiel",
    categoryId: "logistique",
    employmentType: "temps-plein",
    salaryMin: 21,
    salaryMax: 27,
    salaryPeriod: "heure",
    description:
      "Garda World recherche un(e) répartiteur(trice) pour coordonner les interventions des agents sur le terrain. Le poste exige un bon sens de l'organisation et une communication efficace.",
    tags: ["répartition", "service client", "gestion des priorités", "communication"],
    languages: ["fr"],
    postedDaysAgo: 37,
  },
  {
    sourceId: "quebec-emploi",
    url: "https://placement.emploiquebec.gouv.qc.ca/mbe/ut/offre/6601124",
    title: "Planificateur(trice) - chaîne d'approvisionnement",
    company: "Kruger",
    location: "Trois-Rivières, Québec",
    regionId: "mauricie",
    city: "Trois-Rivières",
    remote: "hybride",
    categoryId: "logistique",
    employmentType: "temps-plein",
    salaryMin: 58000,
    salaryMax: 78000,
    salaryPeriod: "annee",
    description:
      "Kruger recherche un(e) planificateur(trice) de la chaîne d'approvisionnement pour optimiser les flux de production et de distribution. Une bonne maîtrise de SAP est un atout important.",
    tags: ["chaîne d'approvisionnement", "SAP", "planification", "prévision de la demande"],
    languages: ["bilingue"],
    postedDaysAgo: 13,
  },

  // --- Production ----------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518434-operateur-de-machine",
    title: "Opérateur(trice) de machine",
    company: "Cascades",
    location: "Drummondville, Québec",
    regionId: "centre-du-quebec",
    city: "Drummondville",
    remote: "presentiel",
    categoryId: "production",
    employmentType: "temps-plein",
    salaryMin: 22,
    salaryMax: 29,
    salaryPeriod: "heure",
    description:
      "Cascades recherche un(e) opérateur(trice) de machine pour ses lignes de production de produits d'emballage. Le respect des normes de santé et sécurité est primordial.",
    tags: ["opération de machine", "production", "santé-sécurité", "assiduité"],
    languages: ["fr"],
    postedDaysAgo: 3,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518435-technicien-de-production",
    title: "Technicien(ne) de production",
    company: "Kruger",
    location: "Rimouski, Québec",
    regionId: "bas-saint-laurent",
    city: "Rimouski",
    remote: "presentiel",
    categoryId: "production",
    employmentType: "temps-plein",
    salaryMin: 24,
    salaryMax: 32,
    salaryPeriod: "heure",
    description:
      "Kruger recherche un(e) technicien(ne) de production pour assurer le bon fonctionnement de ses équipements manufacturiers. Vous effectuerez également des contrôles de qualité réguliers.",
    tags: ["production", "contrôle de qualité", "machinerie", "assiduité"],
    languages: ["fr"],
    postedDaysAgo: 25,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518436-assembleur-aeronautique",
    title: "Assembleur(euse) aéronautique",
    company: "Bombardier",
    location: "Mirabel, Québec",
    regionId: "laurentides",
    city: "Mirabel",
    remote: "presentiel",
    categoryId: "production",
    employmentType: "temps-plein",
    salaryMin: 25,
    salaryMax: 34,
    salaryPeriod: "heure",
    description:
      "Bombardier recherche un(e) assembleur(euse) aéronautique pour son usine d'assemblage final de Mirabel. Précision et minutie sont essentielles pour ce poste.",
    tags: ["assemblage", "aéronautique", "lecture de plans", "minutie"],
    languages: ["bilingue"],
    postedDaysAgo: 8,
  },
  {
    sourceId: "quebec-emploi",
    url: "https://placement.emploiquebec.gouv.qc.ca/mbe/ut/offre/6601125",
    title: "Opérateur(trice) de bétonnière",
    company: "Béton Provincial",
    location: "Sept-Îles, Québec",
    regionId: "cote-nord",
    city: "Sept-Îles",
    remote: "presentiel",
    categoryId: "production",
    employmentType: "saisonnier",
    salaryMin: 23,
    salaryMax: 30,
    salaryPeriod: "heure",
    description:
      "Béton Provincial recherche un(e) opérateur(trice) de bétonnière pour desservir des chantiers sur la Côte-Nord. Le permis de conduire classe 3 est requis.",
    tags: ["conduite de véhicule lourd", "béton", "permis classe 3", "sécurité"],
    languages: ["fr"],
    postedDaysAgo: 44,
  },

  // --- Restauration ------------------------------------------------------------
  {
    sourceId: "jobboom",
    url: "https://www.jobboom.com/fr/emploi/chef-de-cuisine/244002",
    title: "Chef(fe) de cuisine",
    company: "St-Hubert",
    location: "Longueuil, Québec",
    regionId: "monteregie",
    city: "Longueuil",
    remote: "presentiel",
    categoryId: "restauration",
    employmentType: "temps-plein",
    salaryMin: 22,
    salaryMax: 29,
    salaryPeriod: "heure",
    description:
      "St-Hubert recherche un(e) chef(fe) de cuisine pour superviser les opérations culinaires d'un restaurant achalandé. Vous veillerez au respect des normes MAPAQ et à la qualité constante des plats.",
    tags: ["gestion de cuisine", "normes MAPAQ", "planification des menus", "leadership"],
    languages: ["fr"],
    postedDaysAgo: 18,
  },
  {
    sourceId: "jobboom",
    url: "https://www.jobboom.com/fr/emploi/cuisinier/244003",
    title: "Cuisinier(ère)",
    company: "Sépaq",
    location: "Gaspé, Québec",
    regionId: "gaspesie-iles-de-la-madeleine",
    city: "Gaspé",
    remote: "presentiel",
    categoryId: "restauration",
    employmentType: "saisonnier",
    salaryMin: 650,
    salaryMax: 850,
    salaryPeriod: "semaine",
    description:
      "La Sépaq recherche un(e) cuisinier(ère) pour la saison estivale dans un établissement en Gaspésie. Vous préparerez des repas pour les visiteurs dans un cadre naturel exceptionnel.",
    tags: ["restauration", "MAPAQ", "travail d'équipe", "saisonnier"],
    languages: ["fr"],
    postedDaysAgo: 39,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518437-gerant-de-restaurant",
    title: "Gérant(e) de restaurant",
    company: "La Cage - Brasserie sportive",
    location: "Repentigny, Québec",
    regionId: "lanaudiere",
    city: "Repentigny",
    remote: "presentiel",
    categoryId: "restauration",
    employmentType: "temps-plein",
    salaryMin: 45000,
    salaryMax: 58000,
    salaryPeriod: "annee",
    description:
      "La Cage - Brasserie sportive recherche un(e) gérant(e) de restaurant pour superviser l'ensemble des opérations quotidiennes. Vous gérerez une équipe dynamique tout en assurant un service de qualité.",
    tags: ["gestion de restaurant", "service à la clientèle", "gestion d'équipe", "budget"],
    languages: ["fr"],
    postedDaysAgo: 21,
  },

  // --- Arts ----------------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518438-artiste-3d-environnements",
    title: "Artiste 3D - environnements",
    company: "Ubisoft Montréal",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "arts",
    employmentType: "temps-plein",
    salaryMin: 55000,
    salaryMax: 82000,
    salaryPeriod: "annee",
    description:
      "Ubisoft Montréal recherche un(e) artiste 3D pour créer des environnements immersifs pour ses jeux vidéo à succès. La maîtrise de Maya et ZBrush est requise.",
    tags: ["Maya", "ZBrush", "modélisation 3D", "jeux vidéo"],
    languages: ["bilingue"],
    postedDaysAgo: 16,
  },
  {
    sourceId: "espresso-jobs",
    url: "https://www.espresso-jobs.com/fr/emplois/directeur-artistique-90314.html",
    title: "Directeur(trice) artistique",
    company: "Cossette",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "arts",
    employmentType: "contrat",
    salaryMin: 62000,
    salaryMax: 90000,
    salaryPeriod: "annee",
    description:
      "Cossette recherche un(e) directeur(trice) artistique pour concevoir des campagnes publicitaires créatives et mémorables. Vous encadrerez une équipe de designers et de concepteurs-rédacteurs.",
    tags: ["direction artistique", "Adobe Creative Suite", "publicité", "créativité"],
    languages: ["bilingue"],
    postedDaysAgo: 27,
  },

  // --- Science ---------------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518439-stagiaire-recherche-materiaux",
    title: "Stagiaire - recherche en matériaux",
    company: "Hydro-Québec (IREQ)",
    location: "Varennes, Québec",
    regionId: "monteregie",
    city: "Varennes",
    remote: "presentiel",
    categoryId: "science",
    employmentType: "stage",
    salaryMin: 22,
    salaryMax: 28,
    salaryPeriod: "heure",
    description:
      "L'Institut de recherche d'Hydro-Québec recherche un(e) stagiaire en recherche sur les matériaux pour l'été. Vous participerez à des essais en laboratoire sur des matériaux innovants.",
    tags: ["recherche appliquée", "matériaux", "laboratoire", "rédaction scientifique"],
    languages: ["bilingue"],
    postedDaysAgo: 34,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518440-specialiste-modelisation-simulation",
    title: "Spécialiste en modélisation et simulation",
    company: "CAE",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "science",
    employmentType: "temps-plein",
    salaryMin: 68000,
    salaryMax: 98000,
    salaryPeriod: "annee",
    description:
      "CAE recherche un(e) spécialiste en modélisation et simulation pour développer des modèles mathématiques de haute précision. Vous travaillerez sur des simulateurs de vol de calibre mondial.",
    tags: ["modélisation", "simulation", "MATLAB", "analyse de données"],
    languages: ["bilingue"],
    postedDaysAgo: 5,
  },
  {
    sourceId: "randstad-ca",
    url: "https://www.randstad.ca/fr/emplois/metallurgiste/987604/",
    title: "Métallurgiste",
    company: "Pratt & Whitney Canada",
    location: "Longueuil, Québec",
    regionId: "monteregie",
    city: "Longueuil",
    remote: "presentiel",
    categoryId: "science",
    employmentType: "temps-plein",
    salaryMin: 65000,
    salaryMax: 92000,
    salaryPeriod: "annee",
    description:
      "Pratt & Whitney Canada recherche un(e) métallurgiste pour analyser les propriétés des matériaux utilisés dans la fabrication de moteurs d'avion. Vous effectuerez des essais et des analyses de défaillance.",
    tags: ["métallurgie", "contrôle de qualité", "essais de matériaux", "aéronautique"],
    languages: ["fr"],
    postedDaysAgo: 36,
  },

  // --- Direction ---------------------------------------------------------------------
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518441-directeur-des-operations",
    title: "Directeur(trice) des opérations",
    company: "Cascades",
    location: "Kingsey Falls, Québec",
    regionId: "centre-du-quebec",
    city: "Kingsey Falls",
    remote: "presentiel",
    categoryId: "direction",
    employmentType: "temps-plein",
    salaryMin: 110000,
    salaryMax: 150000,
    salaryPeriod: "annee",
    description:
      "Cascades recherche un(e) directeur(trice) des opérations pour superviser l'ensemble des activités manufacturières d'une usine. Vous piloterez des initiatives d'amélioration continue.",
    tags: ["leadership", "opérations manufacturières", "amélioration continue", "gestion budgétaire"],
    languages: ["bilingue"],
    postedDaysAgo: 40,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518442-directeur-regional",
    title: "Directeur(trice) régional(e)",
    company: "Desjardins",
    location: "Québec, Québec",
    regionId: "capitale-nationale",
    city: "Québec",
    remote: "hybride",
    categoryId: "direction",
    employmentType: "temps-plein",
    salaryMin: 105000,
    salaryMax: 145000,
    salaryPeriod: "annee",
    description:
      "Desjardins recherche un(e) directeur(trice) régional(e) pour superviser un réseau de succursales dans la région de Québec. Vous encadrerez les équipes de gestion et développerez les affaires.",
    tags: ["leadership", "gestion de succursales", "développement des affaires", "coaching"],
    languages: ["bilingue"],
    postedDaysAgo: 12,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518443-directeur-de-compte",
    title: "Directeur(trice) de compte",
    company: "CGI",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "direction",
    employmentType: "temps-plein",
    salaryMin: 95000,
    salaryMax: 135000,
    salaryPeriod: "annee",
    description:
      "CGI recherche un(e) directeur(trice) de compte pour gérer et développer des relations stratégiques avec des clients majeurs. Vous serez responsable de la croissance des revenus de votre portefeuille.",
    tags: ["gestion de comptes clients", "vente stratégique", "relations d'affaires", "TI"],
    languages: ["bilingue"],
    postedDaysAgo: 7,
  },

  // --- Autre -----------------------------------------------------------------------
  {
    sourceId: "jobboom",
    url: "https://www.jobboom.com/fr/emploi/garde-parc/244004",
    title: "Garde-parc",
    company: "Sépaq",
    location: "Saguenay, Québec",
    regionId: "saguenay-lac-saint-jean",
    city: "Saguenay",
    remote: "presentiel",
    categoryId: "autre",
    employmentType: "saisonnier",
    salaryMin: 20,
    salaryMax: 26,
    salaryPeriod: "heure",
    description:
      "La Sépaq recherche un(e) garde-parc pour la saison estivale au parc national du Fjord-du-Saguenay. Vous veillerez à la sécurité des visiteurs et à la conservation du territoire.",
    tags: ["conservation", "service à la clientèle", "premiers soins", "plein air"],
    languages: ["fr"],
    postedDaysAgo: 45,
  },
  {
    sourceId: "quebec-emploi",
    url: "https://placement.emploiquebec.gouv.qc.ca/mbe/ut/offre/6601126",
    title: "Agent(e) de sécurité",
    company: "Garda World",
    location: "Laval, Québec",
    regionId: "laval",
    city: "Laval",
    remote: "presentiel",
    categoryId: "autre",
    employmentType: "temps-plein",
    salaryMin: 19,
    salaryMax: 25,
    salaryPeriod: "heure",
    description:
      "Garda World recherche un(e) agent(e) de sécurité pour assurer la surveillance d'un site commercial. Le permis d'agent de sécurité (BSP) est requis.",
    tags: ["sécurité", "surveillance", "permis BSP", "vigilance"],
    languages: ["fr"],
    postedDaysAgo: 2,
  },
  {
    sourceId: "jobillico",
    url: "https://www.jobillico.com/fr/offre-emploi/518444-agent-de-conformite",
    title: "Agent(e) de conformité",
    company: "Loto-Québec",
    location: "Montréal, Québec",
    regionId: "montreal",
    city: "Montréal",
    remote: "hybride",
    categoryId: "autre",
    employmentType: "temps-plein",
    salaryMin: 55000,
    salaryMax: 75000,
    salaryPeriod: "annee",
    description:
      "Loto-Québec recherche un(e) agent(e) de conformité pour veiller au respect des normes réglementaires en matière de jeu responsable. Vous effectuerez des audits internes réguliers.",
    tags: ["conformité réglementaire", "audit", "jeu responsable", "rigueur"],
    languages: ["fr"],
    postedDaysAgo: 31,
  },
];
